// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
namespace Windows.Win32;

[Flags]
internal enum IconInfo : uint
{
    SHGSI_ICONLOCATION = PInvoke.SHGSI_ICONLOCATION, // you always get the icon location
    SHGSI_ICON = 0x000000100, // get icon
    SHGSI_SYSICONINDEX = 0x000004000, // get system icon index
    SHGSI_LINKOVERLAY = 0x000008000, // put a link overlay on icon
    SHGSI_SELECTED = 0x000010000, // show icon in selected state
    SHGSI_LARGEICON = SHGSI_ICONLOCATION, // get large icon
    SHGSI_SMALLICON = 0x000000001, // get small icon
    SHGSI_SHELLICONSIZE = 0x000000004 // get shell size icon
}