// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace RS.Schannel.Manager.API;

public enum TlsCompressionMethodIdentifier : byte
{
    NULL = 0,
    DEFLATE = 1,
    LZS = 64
}