namespace RS.Schannel.Manager.API;

using Windows.Win32;

internal sealed class WindowsCipherSuiteDocumentationService : IWindowsCipherSuiteDocumentationService
{
    private Dictionary<WindowsCipherSuiteListVersion, List<WindowsDocumentationCipherSuiteConfiguration>>? windowsDocumentationCipherSuiteConfigurations;

    public Dictionary<WindowsCipherSuiteListVersion, List<WindowsDocumentationCipherSuiteConfiguration>> GetWindowsDocumentationCipherSuiteConfigurations()
        => windowsDocumentationCipherSuiteConfigurations ??= BuildWindowsDocumentationCipherSuiteConfigurations();

    private static Dictionary<WindowsCipherSuiteListVersion, List<WindowsDocumentationCipherSuiteConfiguration>> BuildWindowsDocumentationCipherSuiteConfigurations()
    {
        var windows11OrServer2022 = new List<WindowsDocumentationCipherSuiteConfiguration>
        {
            new(SslProviderCipherSuiteId.TLS_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_3DES_EDE_CBC_SHA, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA256, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_CHACHA20_POLY1305_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_RC4_56_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT_WITH_RC4_40_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_NULL_SHA384, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_NULL_SHA256, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true)
        };
        var windows10v1903 = new List<WindowsDocumentationCipherSuiteConfiguration>
        {
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_3DES_EDE_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA256, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_RC4_56_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT_WITH_RC4_40_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_NULL_SHA384, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_NULL_SHA256, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true)
        };
        var windows10v1709 = new List<WindowsDocumentationCipherSuiteConfiguration>
        {
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_3DES_EDE_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA256, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_RC4_56_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT_WITH_RC4_40_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_NULL_SHA384, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_NULL_SHA256, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true)
        };
        var windows10v1703 = new List<WindowsDocumentationCipherSuiteConfiguration>
        {
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_3DES_EDE_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_SHA, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_MD5, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA256, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_RC4_56_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT_WITH_RC4_40_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_NULL_SHA384, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_NULL_SHA256, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true)
        };
        var windows10v1607OrServer2016 = new List<WindowsDocumentationCipherSuiteConfiguration>
        {
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_3DES_EDE_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_SHA, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_MD5, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA256, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_RC4_56_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT_WITH_RC4_40_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_NULL_SHA384, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_PSK_WITH_NULL_SHA256, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true)
        };
        var windows10v1511 = new List<WindowsDocumentationCipherSuiteConfiguration>
        {
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_3DES_EDE_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_SHA, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_MD5, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA256, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.SSL_CK_DES_192_EDE3_CBC_WITH_MD5, true, true, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.SSL_CK_RC4_128_WITH_MD5, false, true, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_RC4_56_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT_WITH_RC4_40_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.SSL_CK_DES_64_CBC_WITH_MD5, false, false, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.SSL_CK_RC4_128_EXPORT40_WITH_MD5, false, false, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION })
        };
        var windows81OrServer2012R2 = new List<WindowsDocumentationCipherSuiteConfiguration>
        {
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_3DES_EDE_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_SHA, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_MD5, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.SSL_CK_RC4_128_WITH_MD5, false, true, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.SSL_CK_DES_192_EDE3_CBC_WITH_MD5, true, true, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_DES_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_RC4_56_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT_WITH_RC4_40_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_MD5, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_DES_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.SSL_CK_DES_64_CBC_WITH_MD5, true, false, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.SSL_CK_RC4_128_EXPORT40_WITH_MD5, false, false, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION })
        };
        var windows8OrServer2012 = new List<WindowsDocumentationCipherSuiteConfiguration>
        {
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_3DES_EDE_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_SHA, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_MD5, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.SSL_CK_RC4_128_WITH_MD5, false, true, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.SSL_CK_DES_192_EDE3_CBC_WITH_MD5, true, true, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_DES_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_RC4_56_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT_WITH_RC4_40_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_MD5, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_DES_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.SSL_CK_DES_64_CBC_WITH_MD5, true, false, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.SSL_CK_RC4_128_EXPORT40_WITH_MD5, false, false, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION })
        };
        var windows7OrServer2008R2 = new List<WindowsDocumentationCipherSuiteConfiguration>
        {
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P256_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P384_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_256_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_AES_128_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_3DES_EDE_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_SHA, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_RC4_128_MD5, false, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA256, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_SHA, true, true, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.SSL_CK_RC4_128_WITH_MD5, false, true, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.SSL_CK_DES_192_EDE3_CBC_WITH_MD5, true, true, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION }, true),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION }, false, SslProviderKeyTypeId.TLS_ECC_P521_CURVE_KEY_TYPE),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_DES_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_RC4_56_SHA, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_EXPORT_WITH_RC4_40_MD5, false, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_RSA_WITH_NULL_MD5, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_WITH_DES_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA, true, false, new[] { SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION, SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION, SslProviderProtocolId.SSL3_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.SSL_CK_DES_64_CBC_WITH_MD5, true, false, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION }),
            new(SslProviderCipherSuiteId.SSL_CK_RC4_128_EXPORT40_WITH_MD5, false, false, new[] { SslProviderProtocolId.SSL2_PROTOCOL_VERSION })
        };

        return new Dictionary<WindowsCipherSuiteListVersion, List<WindowsDocumentationCipherSuiteConfiguration>>
        {
            { WindowsCipherSuiteListVersion.Windows11OrServer2022, windows11OrServer2022 },
            { WindowsCipherSuiteListVersion.Windows10v1903, windows10v1903 },
            { WindowsCipherSuiteListVersion.Windows10v1709, windows10v1709 },
            { WindowsCipherSuiteListVersion.Windows10v1703, windows10v1703 },
            { WindowsCipherSuiteListVersion.Windows10v1607OrServer2016, windows10v1607OrServer2016 },
            { WindowsCipherSuiteListVersion.Windows10v1511, windows10v1511 },
            { WindowsCipherSuiteListVersion.Windows81OrServer2012R2, windows81OrServer2012R2 },
            { WindowsCipherSuiteListVersion.Windows8OrServer2012, windows8OrServer2012 },
            { WindowsCipherSuiteListVersion.Windows7OrServer2008R2, windows7OrServer2008R2 },
        };
    }
}