// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
namespace CipherPunk;

using Windows.Win32;

#pragma warning disable CA1028 // Enum Storage should be Int32
public enum BCRYPT_MAGIC : uint
#pragma warning restore CA1028 // Enum Storage should be Int32
{
    BCRYPT_ECDH_PUBLIC_P256_MAGIC = PInvoke.BCRYPT_ECDH_PUBLIC_P256_MAGIC, // ECK1
    BCRYPT_ECDH_PRIVATE_P256_MAGIC = PInvoke.BCRYPT_ECDH_PRIVATE_P256_MAGIC, // ECK2
    BCRYPT_ECDH_PUBLIC_P384_MAGIC = PInvoke.BCRYPT_ECDH_PUBLIC_P384_MAGIC, // ECK3
    BCRYPT_ECDH_PRIVATE_P384_MAGIC = PInvoke.BCRYPT_ECDH_PRIVATE_P384_MAGIC, // ECK4
    BCRYPT_ECDH_PUBLIC_P521_MAGIC = PInvoke.BCRYPT_ECDH_PUBLIC_P521_MAGIC, // ECK5
    BCRYPT_ECDH_PRIVATE_P521_MAGIC = PInvoke.BCRYPT_ECDH_PRIVATE_P521_MAGIC, // ECK6

    BCRYPT_ECDH_PUBLIC_GENERIC_MAGIC = PInvoke.BCRYPT_ECDH_PUBLIC_GENERIC_MAGIC, // ECKP
    BCRYPT_ECDH_PRIVATE_GENERIC_MAGIC = PInvoke.BCRYPT_ECDH_PRIVATE_GENERIC_MAGIC, // ECKV

    BCRYPT_ECDSA_PUBLIC_P256_MAGIC = PInvoke.BCRYPT_ECDSA_PUBLIC_P256_MAGIC, // ECS1
    BCRYPT_ECDSA_PRIVATE_P256_MAGIC = PInvoke.BCRYPT_ECDSA_PRIVATE_P256_MAGIC, // ECS2
    BCRYPT_ECDSA_PUBLIC_P384_MAGIC = PInvoke.BCRYPT_ECDSA_PUBLIC_P384_MAGIC, // ECS3
    BCRYPT_ECDSA_PRIVATE_P384_MAGIC = PInvoke.BCRYPT_ECDSA_PRIVATE_P384_MAGIC, // ECS4
    BCRYPT_ECDSA_PUBLIC_P521_MAGIC = PInvoke.BCRYPT_ECDSA_PUBLIC_P521_MAGIC, // ECS5
    BCRYPT_ECDSA_PRIVATE_P521_MAGIC = PInvoke.BCRYPT_ECDSA_PRIVATE_P521_MAGIC, // ECS6

    BCRYPT_ECDSA_PUBLIC_GENERIC_MAGIC = PInvoke.BCRYPT_ECDSA_PUBLIC_GENERIC_MAGIC, // ECDP
    BCRYPT_ECDSA_PRIVATE_GENERIC_MAGIC = PInvoke.BCRYPT_ECDSA_PRIVATE_GENERIC_MAGIC, // ECDV

    BCRYPT_DH_PUBLIC_MAGIC = 0x42504844, // DHPB
    BCRYPT_DH_PRIVATE_MAGIC = 0x56504844, // DHPV

    BCRYPT_DH_PARAMETERS_MAGIC = PInvoke.BCRYPT_DH_PARAMETERS_MAGIC // DHPM
}