// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable
#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981,SYSLIB1092
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
    namespace Security.Cryptography
    {
        internal struct BCRYPT_ECC_PARAMETER_HEADER
        {
            internal uint dwVersion; //Version of the structure
            internal ECC_CURVE_TYPE_ENUM dwCurveType; //Supported curve types.
            internal ECC_CURVE_ALG_ID_ENUM dwCurveGenerationAlgId; //For X.592 verification purposes, if we include Seed we will need to include the algorithm ID.
            internal uint cbFieldLength; //Byte length of the fields P, A, B, X, Y.
            internal uint cbSubgroupOrder; //Byte length of the subgroup.
            internal uint cbCofactor; //Byte length of cofactor of G in E.
            internal uint cbSeed; //Byte length of the seed used to generate the curve.
            // The rest of the buffer contains the domain parameters
            //P[cbFieldLength]              Prime specifying the base field.
            //A[cbFieldLength]              Coefficient A of the equation y^2 = x^3 + A*x + B mod p
            //B[cbFieldLength]              Coefficient B of the equation y^2 = x^3 + A*x + B mod p
            //Gx[cbFieldLength]             X-coordinate of the base point.
            //Gy[cbFieldLength]             Y-coordinate of the base point.
            //n[cbSubgroupOrder]            Order of the group generated by G = (x,y)
            //h[cbCofactor]                 Cofactor of G in E.
            //S[cbSeed]                     Seed of the curve.
        }
    }
}