// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
namespace CipherPunk;

using Windows.Win32;

internal static class CngPropertyIdentifiers
{
    // BCryptGetProperty strings
    public const string BCRYPT_OBJECT_LENGTH = PInvoke.BCRYPT_OBJECT_LENGTH;
    public const string BCRYPT_ALGORITHM_NAME = PInvoke.BCRYPT_ALGORITHM_NAME;
    public const string BCRYPT_PROVIDER_HANDLE = PInvoke.BCRYPT_PROVIDER_HANDLE;
    public const string BCRYPT_CHAINING_MODE = PInvoke.BCRYPT_CHAINING_MODE;
    public const string BCRYPT_BLOCK_LENGTH = PInvoke.BCRYPT_BLOCK_LENGTH;
    public const string BCRYPT_KEY_LENGTH = PInvoke.BCRYPT_KEY_LENGTH;
    public const string BCRYPT_KEY_OBJECT_LENGTH = PInvoke.BCRYPT_KEY_OBJECT_LENGTH;
    public const string BCRYPT_KEY_STRENGTH = PInvoke.BCRYPT_KEY_STRENGTH;
    public const string BCRYPT_KEY_LENGTHS = PInvoke.BCRYPT_KEY_LENGTHS;
    public const string BCRYPT_BLOCK_SIZE_LIST = PInvoke.BCRYPT_BLOCK_SIZE_LIST;
    public const string BCRYPT_EFFECTIVE_KEY_LENGTH = PInvoke.BCRYPT_EFFECTIVE_KEY_LENGTH;
    public const string BCRYPT_HASH_LENGTH = PInvoke.BCRYPT_HASH_LENGTH;
    public const string BCRYPT_HASH_OID_LIST = PInvoke.BCRYPT_HASH_OID_LIST;
    public const string BCRYPT_PADDING_SCHEMES = PInvoke.BCRYPT_PADDING_SCHEMES;
    public const string BCRYPT_SIGNATURE_LENGTH = PInvoke.BCRYPT_SIGNATURE_LENGTH;
    public const string BCRYPT_HASH_BLOCK_LENGTH = PInvoke.BCRYPT_HASH_BLOCK_LENGTH;
    public const string BCRYPT_AUTH_TAG_LENGTH = PInvoke.BCRYPT_AUTH_TAG_LENGTH;
    public const string BCRYPT_PRIMITIVE_TYPE = PInvoke.BCRYPT_PRIMITIVE_TYPE;
    public const string BCRYPT_IS_KEYED_HASH = PInvoke.BCRYPT_IS_KEYED_HASH;
    public const string BCRYPT_IS_REUSABLE_HASH = PInvoke.BCRYPT_IS_REUSABLE_HASH;
    public const string BCRYPT_MESSAGE_BLOCK_LENGTH = PInvoke.BCRYPT_MESSAGE_BLOCK_LENGTH;
    public const string BCRYPT_PUBLIC_KEY_LENGTH = PInvoke.BCRYPT_PUBLIC_KEY_LENGTH;

    // Additional BCryptGetProperty strings for the RNG Platform Crypto Provider
    public const string BCRYPT_PCP_PLATFORM_TYPE_PROPERTY = PInvoke.BCRYPT_PCP_PLATFORM_TYPE_PROPERTY;
    public const string BCRYPT_PCP_PROVIDER_VERSION_PROPERTY = PInvoke.BCRYPT_PCP_PROVIDER_VERSION_PROPERTY;

    // Additional properties for the HKDF on BCRYPT_KEY_HANDLE (and BCRYPT_SECRET_HANDLE).
    public const string BCRYPT_MULTI_OBJECT_LENGTH = PInvoke.BCRYPT_MULTI_OBJECT_LENGTH;
    public const string BCRYPT_IS_IFX_TPM_WEAK_KEY = PInvoke.BCRYPT_IS_IFX_TPM_WEAK_KEY;
    public const string BCRYPT_HKDF_HASH_ALGORITHM = PInvoke.BCRYPT_HKDF_HASH_ALGORITHM;
    public const string BCRYPT_HKDF_SALT_AND_FINALIZE = PInvoke.BCRYPT_HKDF_SALT_AND_FINALIZE;
    public const string BCRYPT_HKDF_PRK_AND_FINALIZE = PInvoke.BCRYPT_HKDF_PRK_AND_FINALIZE;

    // Property Strings for DH
    public const string BCRYPT_DH_PARAMETERS = PInvoke.BCRYPT_DH_PARAMETERS;

    // Property Strings for ECC
    public const string BCRYPT_ECC_PARAMETERS = PInvoke.BCRYPT_ECC_PARAMETERS;
    public const string BCRYPT_ECC_CURVE_NAME = PInvoke.BCRYPT_ECC_CURVE_NAME;
    public const string BCRYPT_ECC_CURVE_NAME_LIST = PInvoke.BCRYPT_ECC_CURVE_NAME_LIST;

    // Standard property names.
    public const string NCRYPT_NAME_PROPERTY = PInvoke.NCRYPT_NAME_PROPERTY;
    public const string NCRYPT_UNIQUE_NAME_PROPERTY = PInvoke.NCRYPT_UNIQUE_NAME_PROPERTY;
    public const string NCRYPT_ALGORITHM_PROPERTY = PInvoke.NCRYPT_ALGORITHM_PROPERTY;
    public const string NCRYPT_LENGTH_PROPERTY = PInvoke.NCRYPT_LENGTH_PROPERTY;
    public const string NCRYPT_LENGTHS_PROPERTY = PInvoke.NCRYPT_LENGTHS_PROPERTY;
    public const string NCRYPT_BLOCK_LENGTH_PROPERTY = PInvoke.NCRYPT_BLOCK_LENGTH_PROPERTY;

    public const string NCRYPT_PUBLIC_LENGTH_PROPERTY = PInvoke.NCRYPT_PUBLIC_LENGTH_PROPERTY;
    public const string NCRYPT_SIGNATURE_LENGTH_PROPERTY = PInvoke.NCRYPT_SIGNATURE_LENGTH_PROPERTY;
    public const string NCRYPT_CHAINING_MODE_PROPERTY = PInvoke.NCRYPT_CHAINING_MODE_PROPERTY;
    public const string NCRYPT_AUTH_TAG_LENGTH = PInvoke.NCRYPT_AUTH_TAG_LENGTH;
    public const string NCRYPT_UI_POLICY_PROPERTY = PInvoke.NCRYPT_UI_POLICY_PROPERTY;
    public const string NCRYPT_EXPORT_POLICY_PROPERTY = PInvoke.NCRYPT_EXPORT_POLICY_PROPERTY;
    public const string NCRYPT_WINDOW_HANDLE_PROPERTY = PInvoke.NCRYPT_WINDOW_HANDLE_PROPERTY;
    public const string NCRYPT_USE_CONTEXT_PROPERTY = PInvoke.NCRYPT_USE_CONTEXT_PROPERTY;
    public const string NCRYPT_IMPL_TYPE_PROPERTY = PInvoke.NCRYPT_IMPL_TYPE_PROPERTY;
    public const string NCRYPT_KEY_USAGE_PROPERTY = PInvoke.NCRYPT_KEY_USAGE_PROPERTY;
    public const string NCRYPT_KEY_TYPE_PROPERTY = PInvoke.NCRYPT_KEY_TYPE_PROPERTY;
    public const string NCRYPT_VERSION_PROPERTY = PInvoke.NCRYPT_VERSION_PROPERTY;
    public const string NCRYPT_SECURITY_DESCR_SUPPORT_PROPERTY = PInvoke.NCRYPT_SECURITY_DESCR_SUPPORT_PROPERTY;
    public const string NCRYPT_SECURITY_DESCR_PROPERTY = PInvoke.NCRYPT_SECURITY_DESCR_PROPERTY;
    public const string NCRYPT_USE_COUNT_ENABLED_PROPERTY = PInvoke.NCRYPT_USE_COUNT_ENABLED_PROPERTY;
    public const string NCRYPT_USE_COUNT_PROPERTY = PInvoke.NCRYPT_USE_COUNT_PROPERTY;
    public const string NCRYPT_LAST_MODIFIED_PROPERTY = PInvoke.NCRYPT_LAST_MODIFIED_PROPERTY;
    public const string NCRYPT_MAX_NAME_LENGTH_PROPERTY = PInvoke.NCRYPT_MAX_NAME_LENGTH_PROPERTY;
    public const string NCRYPT_ALGORITHM_GROUP_PROPERTY = PInvoke.NCRYPT_ALGORITHM_GROUP_PROPERTY;
    public const string NCRYPT_DH_PARAMETERS_PROPERTY = PInvoke.NCRYPT_DH_PARAMETERS_PROPERTY;
    public const string NCRYPT_ECC_PARAMETERS_PROPERTY = PInvoke.NCRYPT_ECC_PARAMETERS_PROPERTY;
    public const string NCRYPT_ECC_CURVE_NAME_PROPERTY = PInvoke.NCRYPT_ECC_CURVE_NAME_PROPERTY;
    public const string NCRYPT_ECC_CURVE_NAME_LIST_PROPERTY = PInvoke.NCRYPT_ECC_CURVE_NAME_LIST_PROPERTY;
    public const string NCRYPT_USE_VIRTUAL_ISOLATION_PROPERTY = PInvoke.NCRYPT_USE_VIRTUAL_ISOLATION_PROPERTY;
    public const string NCRYPT_USE_PER_BOOT_KEY_PROPERTY = PInvoke.NCRYPT_USE_PER_BOOT_KEY_PROPERTY;
    public const string NCRYPT_PROVIDER_HANDLE_PROPERTY = PInvoke.NCRYPT_PROVIDER_HANDLE_PROPERTY;
    public const string NCRYPT_PIN_PROPERTY = PInvoke.NCRYPT_PIN_PROPERTY;
    public const string NCRYPT_READER_PROPERTY = PInvoke.NCRYPT_READER_PROPERTY;
    public const string NCRYPT_SMARTCARD_GUID_PROPERTY = PInvoke.NCRYPT_SMARTCARD_GUID_PROPERTY;
    public const string NCRYPT_CERTIFICATE_PROPERTY = PInvoke.NCRYPT_CERTIFICATE_PROPERTY;
    public const string NCRYPT_PIN_PROMPT_PROPERTY = PInvoke.NCRYPT_PIN_PROMPT_PROPERTY;
    public const string NCRYPT_USER_CERTSTORE_PROPERTY = PInvoke.NCRYPT_USER_CERTSTORE_PROPERTY;
    public const string NCRYPT_ROOT_CERTSTORE_PROPERTY = PInvoke.NCRYPT_ROOT_CERTSTORE_PROPERTY;
    public const string NCRYPT_SECURE_PIN_PROPERTY = PInvoke.NCRYPT_SECURE_PIN_PROPERTY;
    public const string NCRYPT_ASSOCIATED_ECDH_KEY = PInvoke.NCRYPT_ASSOCIATED_ECDH_KEY;
    public const string NCRYPT_SCARD_PIN_ID = PInvoke.NCRYPT_SCARD_PIN_ID;
    public const string NCRYPT_SCARD_PIN_INFO = PInvoke.NCRYPT_SCARD_PIN_INFO;
    public const string NCRYPT_READER_ICON_PROPERTY = PInvoke.NCRYPT_READER_ICON_PROPERTY;
    public const string NCRYPT_KDF_SECRET_VALUE = PInvoke.NCRYPT_KDF_SECRET_VALUE;
    public const string NCRYPT_DISMISS_UI_TIMEOUT_SEC_PROPERTY = PInvoke.NCRYPT_DISMISS_UI_TIMEOUT_SEC_PROPERTY;

    ////
    //// Additional property strings specific for the Platform Crypto Provider
    ////
    public const string NCRYPT_PCP_PLATFORM_TYPE_PROPERTY = PInvoke.NCRYPT_PCP_PLATFORM_TYPE_PROPERTY;
    public const string NCRYPT_PCP_PROVIDER_VERSION_PROPERTY = PInvoke.NCRYPT_PCP_PROVIDER_VERSION_PROPERTY;
    public const string NCRYPT_PCP_EKPUB_PROPERTY = PInvoke.NCRYPT_PCP_EKPUB_PROPERTY;
    public const string NCRYPT_PCP_EKCERT_PROPERTY = PInvoke.NCRYPT_PCP_EKCERT_PROPERTY;
    public const string NCRYPT_PCP_EKNVCERT_PROPERTY = PInvoke.NCRYPT_PCP_EKNVCERT_PROPERTY;
    public const string NCRYPT_PCP_RSA_EKPUB_PROPERTY = PInvoke.NCRYPT_PCP_RSA_EKPUB_PROPERTY;
    public const string NCRYPT_PCP_RSA_EKCERT_PROPERTY = PInvoke.NCRYPT_PCP_RSA_EKCERT_PROPERTY;
    public const string NCRYPT_PCP_RSA_EKNVCERT_PROPERTY = PInvoke.NCRYPT_PCP_RSA_EKNVCERT_PROPERTY;
    public const string NCRYPT_PCP_ECC_EKPUB_PROPERTY = PInvoke.NCRYPT_PCP_ECC_EKPUB_PROPERTY;
    public const string NCRYPT_PCP_ECC_EKCERT_PROPERTY = PInvoke.NCRYPT_PCP_ECC_EKCERT_PROPERTY;
    public const string NCRYPT_PCP_ECC_EKNVCERT_PROPERTY = PInvoke.NCRYPT_PCP_ECC_EKNVCERT_PROPERTY;
    public const string NCRYPT_PCP_SRKPUB_PROPERTY = PInvoke.NCRYPT_PCP_SRKPUB_PROPERTY;
    public const string NCRYPT_PCP_PCRTABLE_PROPERTY = PInvoke.NCRYPT_PCP_PCRTABLE_PROPERTY;
    public const string NCRYPT_PCP_CHANGEPASSWORD_PROPERTY = PInvoke.NCRYPT_PCP_CHANGEPASSWORD_PROPERTY;
    public const string NCRYPT_PCP_PASSWORD_REQUIRED_PROPERTY = PInvoke.NCRYPT_PCP_PASSWORD_REQUIRED_PROPERTY;
    public const string NCRYPT_PCP_USAGEAUTH_PROPERTY = PInvoke.NCRYPT_PCP_USAGEAUTH_PROPERTY;
    public const string NCRYPT_PCP_MIGRATIONPASSWORD_PROPERTY = PInvoke.NCRYPT_PCP_MIGRATIONPASSWORD_PROPERTY;
    public const string NCRYPT_PCP_EXPORT_ALLOWED_PROPERTY = PInvoke.NCRYPT_PCP_EXPORT_ALLOWED_PROPERTY;
    public const string NCRYPT_PCP_STORAGEPARENT_PROPERTY = PInvoke.NCRYPT_PCP_STORAGEPARENT_PROPERTY;
    public const string NCRYPT_PCP_PROVIDERHANDLE_PROPERTY = PInvoke.NCRYPT_PCP_PROVIDERHANDLE_PROPERTY;
    public const string NCRYPT_PCP_PLATFORMHANDLE_PROPERTY = PInvoke.NCRYPT_PCP_PLATFORMHANDLE_PROPERTY;
    public const string NCRYPT_PCP_PLATFORM_BINDING_PCRMASK_PROPERTY = PInvoke.NCRYPT_PCP_PLATFORM_BINDING_PCRMASK_PROPERTY;
    public const string NCRYPT_PCP_PLATFORM_BINDING_PCRDIGESTLIST_PROPERTY = PInvoke.NCRYPT_PCP_PLATFORM_BINDING_PCRDIGESTLIST_PROPERTY;
    public const string NCRYPT_PCP_PLATFORM_BINDING_PCRDIGEST_PROPERTY = PInvoke.NCRYPT_PCP_PLATFORM_BINDING_PCRDIGEST_PROPERTY;
    public const string NCRYPT_PCP_KEY_USAGE_POLICY_PROPERTY = PInvoke.NCRYPT_PCP_KEY_USAGE_POLICY_PROPERTY;
    public const string NCRYPT_PCP_RSA_SCHEME_PROPERTY = PInvoke.NCRYPT_PCP_RSA_SCHEME_PROPERTY;
    public const string NCRYPT_PCP_TPM12_IDBINDING_PROPERTY = PInvoke.NCRYPT_PCP_TPM12_IDBINDING_PROPERTY;
    public const string NCRYPT_PCP_TPM12_IDBINDING_DYNAMIC_PROPERTY = PInvoke.NCRYPT_PCP_TPM12_IDBINDING_DYNAMIC_PROPERTY;
    public const string NCRYPT_PCP_TPM12_IDACTIVATION_PROPERTY = PInvoke.NCRYPT_PCP_TPM12_IDACTIVATION_PROPERTY;
    public const string NCRYPT_PCP_KEYATTESTATION_PROPERTY = PInvoke.NCRYPT_PCP_KEYATTESTATION_PROPERTY;
    public const string NCRYPT_PCP_ALTERNATE_KEY_STORAGE_LOCATION_PROPERTY = PInvoke.NCRYPT_PCP_ALTERNATE_KEY_STORAGE_LOCATION_PROPERTY;
    public const string NCRYPT_PCP_PLATFORM_BINDING_PCRALGID_PROPERTY = PInvoke.NCRYPT_PCP_PLATFORM_BINDING_PCRALGID_PROPERTY;
    public const string NCRYPT_PCP_HMAC_AUTH_POLICYREF = PInvoke.NCRYPT_PCP_HMAC_AUTH_POLICYREF;
    public const string NCRYPT_PCP_HMAC_AUTH_POLICYINFO = PInvoke.NCRYPT_PCP_HMAC_AUTH_POLICYINFO;
    public const string NCRYPT_PCP_HMAC_AUTH_NONCE = PInvoke.NCRYPT_PCP_HMAC_AUTH_NONCE;
    public const string NCRYPT_PCP_HMAC_AUTH_SIGNATURE = PInvoke.NCRYPT_PCP_HMAC_AUTH_SIGNATURE;
    public const string NCRYPT_PCP_HMAC_AUTH_TICKET = PInvoke.NCRYPT_PCP_HMAC_AUTH_TICKET;
    public const string NCRYPT_PCP_NO_DA_PROTECTION_PROPERTY = PInvoke.NCRYPT_PCP_NO_DA_PROTECTION_PROPERTY;
    public const string NCRYPT_PCP_TPM_MANUFACTURER_ID_PROPERTY = PInvoke.NCRYPT_PCP_TPM_MANUFACTURER_ID_PROPERTY;
    public const string NCRYPT_PCP_TPM_FW_VERSION_PROPERTY = PInvoke.NCRYPT_PCP_TPM_FW_VERSION_PROPERTY;
    public const string NCRYPT_PCP_TPM2BNAME_PROPERTY = PInvoke.NCRYPT_PCP_TPM2BNAME_PROPERTY;
    public const string NCRYPT_PCP_TPM_VERSION_PROPERTY = PInvoke.NCRYPT_PCP_TPM_VERSION_PROPERTY;
    public const string NCRYPT_PCP_RAW_POLICYDIGEST_PROPERTY = PInvoke.NCRYPT_PCP_RAW_POLICYDIGEST_PROPERTY;
    public const string NCRYPT_PCP_KEY_CREATIONHASH_PROPERTY = PInvoke.NCRYPT_PCP_KEY_CREATIONHASH_PROPERTY;
    public const string NCRYPT_PCP_KEY_CREATIONTICKET_PROPERTY = PInvoke.NCRYPT_PCP_KEY_CREATIONTICKET_PROPERTY;
    public const string NCRYPT_PCP_RSA_SCHEME_HASH_ALG_PROPERTY = PInvoke.NCRYPT_PCP_RSA_SCHEME_HASH_ALG_PROPERTY;
    public const string NCRYPT_PCP_TPM_IFX_RSA_KEYGEN_PROHIBITED_PROPERTY = PInvoke.NCRYPT_PCP_TPM_IFX_RSA_KEYGEN_PROHIBITED_PROPERTY;
    public const string NCRYPT_PCP_TPM_IFX_RSA_KEYGEN_VULNERABILITY_PROPERTY = PInvoke.NCRYPT_PCP_TPM_IFX_RSA_KEYGEN_VULNERABILITY_PROPERTY;

    public const string NCRYPT_PCP_SESSIONID_PROPERTY = PInvoke.NCRYPT_PCP_SESSIONID_PROPERTY;
    public const string NCRYPT_PCP_PSS_SALT_SIZE_PROPERTY = PInvoke.NCRYPT_PCP_PSS_SALT_SIZE_PROPERTY;

    public const string NCRYPT_PCP_INTERMEDIATE_CA_EKCERT_PROPERTY = PInvoke.NCRYPT_PCP_INTERMEDIATE_CA_EKCERT_PROPERTY;
    public const string NCRYPT_PCP_PCRTABLE_ALGORITHM_PROPERTY = PInvoke.NCRYPT_PCP_PCRTABLE_ALGORITHM_PROPERTY;
    public const string NCRYPT_PCP_SYMMETRIC_KEYBITS_PROPERTY = PInvoke.NCRYPT_PCP_SYMMETRIC_KEYBITS_PROPERTY;
}