// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
namespace CipherPunk;

using Windows.Win32;

public enum CRYPT_OID_GROUP_ID : uint
{
    CRYPT_ALL_OID_GROUP_ID = 0U,
    CRYPT_HASH_ALG_OID_GROUP_ID = PInvoke.CRYPT_HASH_ALG_OID_GROUP_ID,
    CRYPT_ENCRYPT_ALG_OID_GROUP_ID = PInvoke.CRYPT_ENCRYPT_ALG_OID_GROUP_ID,
    CRYPT_PUBKEY_ALG_OID_GROUP_ID = PInvoke.CRYPT_PUBKEY_ALG_OID_GROUP_ID,
    CRYPT_SIGN_ALG_OID_GROUP_ID = PInvoke.CRYPT_SIGN_ALG_OID_GROUP_ID,
    CRYPT_RDN_ATTR_OID_GROUP_ID = PInvoke.CRYPT_RDN_ATTR_OID_GROUP_ID,
    CRYPT_EXT_OR_ATTR_OID_GROUP_ID = PInvoke.CRYPT_EXT_OR_ATTR_OID_GROUP_ID,
    CRYPT_ENHKEY_USAGE_OID_GROUP_ID = PInvoke.CRYPT_ENHKEY_USAGE_OID_GROUP_ID,
    CRYPT_POLICY_OID_GROUP_ID = PInvoke.CRYPT_POLICY_OID_GROUP_ID,
    CRYPT_TEMPLATE_OID_GROUP_ID = PInvoke.CRYPT_TEMPLATE_OID_GROUP_ID,
    CRYPT_KDF_OID_GROUP_ID = PInvoke.CRYPT_KDF_OID_GROUP_ID,
    CRYPT_LAST_OID_GROUP_ID = PInvoke.CRYPT_LAST_OID_GROUP_ID,

    CRYPT_FIRST_ALG_OID_GROUP_ID = CRYPT_HASH_ALG_OID_GROUP_ID,
    CRYPT_LAST_ALG_OID_GROUP_ID = CRYPT_SIGN_ALG_OID_GROUP_ID
}