// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
namespace CipherPunk;

using Windows.Win32;

public static class CryptographicPrimitiveProviders
{
    //
    // Microsoft built-in providers.
    //
    public const string MS_PRIMITIVE_PROVIDER = PInvoke.MS_PRIMITIVE_PROVIDER;
    public const string MS_PLATFORM_CRYPTO_PROVIDER = PInvoke.MS_PLATFORM_CRYPTO_PROVIDER;
}