// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
using Windows.Win32;

namespace CipherPunk;

[Flags]
#pragma warning disable CA1028 // Enum Storage should be Int32
public enum CRYPT_OID_FLAG : uint
#pragma warning restore CA1028 // Enum Storage should be Int32
{
    CRYPT_OID_INHIBIT_SIGNATURE_FORMAT_FLAG = PInvoke.CRYPT_OID_INHIBIT_SIGNATURE_FORMAT_FLAG,
    CRYPT_OID_USE_PUBKEY_PARA_FOR_PKCS7_FLAG = PInvoke.CRYPT_OID_USE_PUBKEY_PARA_FOR_PKCS7_FLAG,
    CRYPT_OID_NO_NULL_ALGORITHM_PARA_FLAG = PInvoke.CRYPT_OID_NO_NULL_ALGORITHM_PARA_FLAG,

    CRYPT_OID_PUBKEY_SIGN_ONLY_FLAG = PInvoke.CRYPT_OID_PUBKEY_SIGN_ONLY_FLAG,
    CRYPT_OID_PUBKEY_ENCRYPT_ONLY_FLAG = PInvoke.CRYPT_OID_PUBKEY_ENCRYPT_ONLY_FLAG,
    CRYPT_OID_USE_CURVE_NAME_FOR_ENCODE_FLAG = PInvoke.CRYPT_OID_USE_CURVE_NAME_FOR_ENCODE_FLAG,
    CRYPT_OID_USE_CURVE_PARAMETERS_FOR_ENCODE_FLAG = PInvoke.CRYPT_OID_USE_CURVE_PARAMETERS_FOR_ENCODE_FLAG
}