// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
namespace CipherPunk;

using Windows.Win32;

internal enum GPO_SECTION : uint
{
    // Group Policy Object Section flags
    GPO_SECTION_ROOT = PInvoke.GPO_SECTION_ROOT, // Root
    GPO_SECTION_USER = PInvoke.GPO_SECTION_USER, // User
    GPO_SECTION_MACHINE = PInvoke.GPO_SECTION_MACHINE // Machine
}