// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable
#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981,SYSLIB1092
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32;

internal struct NCRYPT_SSL_CIPHER_SUITE
{
    internal SslProviderProtocolId dwProtocol;

    internal SslProviderCipherSuiteId dwCipherSuite;

    internal SslProviderCipherSuiteId dwBaseCipherSuite;

    internal __char_64 szCipherSuite;

    internal __char_64 szCipher;

    internal uint dwCipherLen;

    internal uint dwCipherBlockLen;

    internal __char_64 szHash;

    internal uint dwHashLen;

    internal __char_64 szExchange;

    internal uint dwMinExchangeLen;

    internal uint dwMaxExchangeLen;

    internal __char_64 szCertificate;

    internal SslProviderKeyTypeId dwKeyType;

    //internal __char_64 szCipherMode;
}