// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
namespace Windows.Win32;

public enum SslProviderProtocolId : ushort
{
    SSL2_PROTOCOL_VERSION = 0x0002,
    SSL3_PROTOCOL_VERSION = 0x0300,
    //TLS1_PROTOCOL_VERSION = TLS1_PROTOCOL_VERSION,
    TLS1_0_PROTOCOL_VERSION = 0x0301,
    TLS1_1_PROTOCOL_VERSION = 0x0302,
    TLS1_2_PROTOCOL_VERSION = 0x0303,
    TLS1_3_PROTOCOL_VERSION = 0x0304,
    DTLS1_0_PROTOCOL_VERSION = 0xfeff,
    DTLS1_2_PROTOCOL_VERSION = 0xfefd
}