// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436
namespace RS.Schannel.Manager.API;

public enum BCRYPT_MAGIC : uint
{
    BCRYPT_ECDH_PUBLIC_P256_MAGIC = 0x314B4345,  // ECK1
    BCRYPT_ECDH_PRIVATE_P256_MAGIC = 0x324B4345, // ECK2
    BCRYPT_ECDH_PUBLIC_P384_MAGIC = 0x334B4345, // ECK3
    BCRYPT_ECDH_PRIVATE_P384_MAGIC = 0x344B4345, // ECK4
    BCRYPT_ECDH_PUBLIC_P521_MAGIC = 0x354B4345, // ECK5
    BCRYPT_ECDH_PRIVATE_P521_MAGIC = 0x364B4345, // ECK6

    BCRYPT_ECDH_PUBLIC_GENERIC_MAGIC = 0x504B4345, // ECKP
    BCRYPT_ECDH_PRIVATE_GENERIC_MAGIC = 0x564B4345, // ECKV

    BCRYPT_ECDSA_PUBLIC_P256_MAGIC = 0x31534345, // ECS1
    BCRYPT_ECDSA_PRIVATE_P256_MAGIC = 0x32534345, // ECS2
    BCRYPT_ECDSA_PUBLIC_P384_MAGIC = 0x33534345, // ECS3
    BCRYPT_ECDSA_PRIVATE_P384_MAGIC = 0x34534345, // ECS4
    BCRYPT_ECDSA_PUBLIC_P521_MAGIC = 0x35534345, // ECS5
    BCRYPT_ECDSA_PRIVATE_P521_MAGIC = 0x36534345, // ECS6

    BCRYPT_ECDSA_PUBLIC_GENERIC_MAGIC = 0x50444345, // ECDP
    BCRYPT_ECDSA_PRIVATE_GENERIC_MAGIC = 0x56444345, // ECDV
}