// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436
namespace RS.Schannel.Manager.API;

public static class CngPropertyIdentifiers
{
    // BCryptGetProperty strings
    public const string BCRYPT_OBJECT_LENGTH = "ObjectLength";
    public const string BCRYPT_ALGORITHM_NAME = "AlgorithmName";
    public const string BCRYPT_PROVIDER_HANDLE = "ProviderHandle";
    public const string BCRYPT_CHAINING_MODE = "ChainingMode";
    public const string BCRYPT_BLOCK_LENGTH = "BlockLength";
    public const string BCRYPT_KEY_LENGTH = "KeyLength";
    public const string BCRYPT_KEY_OBJECT_LENGTH = "KeyObjectLength";
    public const string BCRYPT_KEY_STRENGTH = "KeyStrength";
    public const string BCRYPT_KEY_LENGTHS = "KeyLengths";
    public const string BCRYPT_BLOCK_SIZE_LIST = "BlockSizeList";
    public const string BCRYPT_EFFECTIVE_KEY_LENGTH = "EffectiveKeyLength";
    public const string BCRYPT_HASH_LENGTH = "HashDigestLength";
    public const string BCRYPT_HASH_OID_LIST = "HashOIDList";
    public const string BCRYPT_PADDING_SCHEMES = "PaddingSchemes";
    public const string BCRYPT_SIGNATURE_LENGTH = "SignatureLength";
    public const string BCRYPT_HASH_BLOCK_LENGTH = "HashBlockLength";
    public const string BCRYPT_AUTH_TAG_LENGTH = "AuthTagLength";
    public const string BCRYPT_PRIMITIVE_TYPE = "PrimitiveType";
    public const string BCRYPT_IS_KEYED_HASH = "IsKeyedHash";
    public const string BCRYPT_IS_REUSABLE_HASH = "IsReusableHash";
    public const string BCRYPT_MESSAGE_BLOCK_LENGTH = "MessageBlockLength";
    public const string BCRYPT_PUBLIC_KEY_LENGTH = "PublicKeyLength";

    // Additional BCryptGetProperty strings for the RNG Platform Crypto Provider
    public const string BCRYPT_PCP_PLATFORM_TYPE_PROPERTY = "PCP_PLATFORM_TYPE";
    public const string BCRYPT_PCP_PROVIDER_VERSION_PROPERTY = "PCP_PROVIDER_VERSION";

    // Additional properties for the HKDF on BCRYPT_KEY_HANDLE (and BCRYPT_SECRET_HANDLE).
    public const string BCRYPT_MULTI_OBJECT_LENGTH = "MultiObjectLength";
    public const string BCRYPT_IS_IFX_TPM_WEAK_KEY = "IsIfxTpmWeakKey";
    public const string BCRYPT_HKDF_HASH_ALGORITHM = "HkdfHashAlgorithm";
    public const string BCRYPT_HKDF_SALT_AND_FINALIZE = "HkdfSaltAndFinalize";
    public const string BCRYPT_HKDF_PRK_AND_FINALIZE = "HkdfPrkAndFinalize";

    // Property Strings for DH
    public const string BCRYPT_DH_PARAMETERS = "DHParameters";

    //Property Strings for ECC
    public const string BCRYPT_ECC_PARAMETERS = "ECCParameters";
    public const string BCRYPT_ECC_CURVE_NAME = "ECCCurveName";
    public const string BCRYPT_ECC_CURVE_NAME_LIST = "ECCCurveNameList";

    // Standard property names.
    public const string NCRYPT_NAME_PROPERTY = "Name";
    public const string NCRYPT_UNIQUE_NAME_PROPERTY = "Unique Name";
    public const string NCRYPT_ALGORITHM_PROPERTY = "Algorithm Name";
    public const string NCRYPT_LENGTH_PROPERTY = "Length";
    public const string NCRYPT_LENGTHS_PROPERTY = "Lengths";
    public const string NCRYPT_BLOCK_LENGTH_PROPERTY = "Block Length";

    public const string NCRYPT_PUBLIC_LENGTH_PROPERTY = BCRYPT_PUBLIC_KEY_LENGTH;
    public const string NCRYPT_SIGNATURE_LENGTH_PROPERTY = BCRYPT_SIGNATURE_LENGTH;
    public const string NCRYPT_CHAINING_MODE_PROPERTY = "Chaining Mode";
    public const string NCRYPT_AUTH_TAG_LENGTH = "AuthTagLength";
    public const string NCRYPT_UI_POLICY_PROPERTY = "UI Policy";
    public const string NCRYPT_EXPORT_POLICY_PROPERTY = "Export Policy";
    public const string NCRYPT_WINDOW_HANDLE_PROPERTY = "HWND Handle";
    public const string NCRYPT_USE_CONTEXT_PROPERTY = "Use Context";
    public const string NCRYPT_IMPL_TYPE_PROPERTY = "Impl Type";
    public const string NCRYPT_KEY_USAGE_PROPERTY = "Key Usage";
    public const string NCRYPT_KEY_TYPE_PROPERTY = "Key Type";
    public const string NCRYPT_VERSION_PROPERTY = "Version";
    public const string NCRYPT_SECURITY_DESCR_SUPPORT_PROPERTY = "Security Descr Support";
    public const string NCRYPT_SECURITY_DESCR_PROPERTY = "Security Descr";
    public const string NCRYPT_USE_COUNT_ENABLED_PROPERTY = "Enabled Use Count";
    public const string NCRYPT_USE_COUNT_PROPERTY = "Use Count";
    public const string NCRYPT_LAST_MODIFIED_PROPERTY = "Modified";
    public const string NCRYPT_MAX_NAME_LENGTH_PROPERTY = "Max Name Length";
    public const string NCRYPT_ALGORITHM_GROUP_PROPERTY = "Algorithm Group";
    public const string NCRYPT_DH_PARAMETERS_PROPERTY = BCRYPT_DH_PARAMETERS;
    public const string NCRYPT_ECC_PARAMETERS_PROPERTY = BCRYPT_ECC_PARAMETERS;
    public const string NCRYPT_ECC_CURVE_NAME_PROPERTY = BCRYPT_ECC_CURVE_NAME;
    public const string NCRYPT_ECC_CURVE_NAME_LIST_PROPERTY = BCRYPT_ECC_CURVE_NAME_LIST;
    public const string NCRYPT_USE_VIRTUAL_ISOLATION_PROPERTY = "Virtual Iso";
    public const string NCRYPT_USE_PER_BOOT_KEY_PROPERTY = "Per Boot Key";
    public const string NCRYPT_PROVIDER_HANDLE_PROPERTY = "Provider Handle";
    public const string NCRYPT_PIN_PROPERTY = "SmartCardPin";
    public const string NCRYPT_READER_PROPERTY = "SmartCardReader";
    public const string NCRYPT_SMARTCARD_GUID_PROPERTY = "SmartCardGuid";
    public const string NCRYPT_CERTIFICATE_PROPERTY = "SmartCardKeyCertificate";
    public const string NCRYPT_PIN_PROMPT_PROPERTY = "SmartCardPinPrompt";
    public const string NCRYPT_USER_CERTSTORE_PROPERTY = "SmartCardUserCertStore";
    public const string NCRYPT_ROOT_CERTSTORE_PROPERTY = "SmartcardRootCertStore";
    public const string NCRYPT_SECURE_PIN_PROPERTY = "SmartCardSecurePin";
    public const string NCRYPT_ASSOCIATED_ECDH_KEY = "SmartCardAssociatedECDHKey";
    public const string NCRYPT_SCARD_PIN_ID = "SmartCardPinId";
    public const string NCRYPT_SCARD_PIN_INFO = "SmartCardPinInfo";
    public const string NCRYPT_READER_ICON_PROPERTY = "SmartCardReaderIcon";
    public const string NCRYPT_KDF_SECRET_VALUE = "KDFKeySecret";
    public const string NCRYPT_DISMISS_UI_TIMEOUT_SEC_PROPERTY = "SmartCardDismissUITimeoutSeconds";

    //
    // Additional property strings specific for the Platform Crypto Provider
    //
    public const string NCRYPT_PCP_PLATFORM_TYPE_PROPERTY = "PCP_PLATFORM_TYPE";
    public const string NCRYPT_PCP_PROVIDER_VERSION_PROPERTY = "PCP_PROVIDER_VERSION";
    public const string NCRYPT_PCP_EKPUB_PROPERTY = "PCP_EKPUB";
    public const string NCRYPT_PCP_EKCERT_PROPERTY = "PCP_EKCERT";
    public const string NCRYPT_PCP_EKNVCERT_PROPERTY = "PCP_EKNVCERT";
    public const string NCRYPT_PCP_RSA_EKPUB_PROPERTY = "PCP_RSA_EKPUB";
    public const string NCRYPT_PCP_RSA_EKCERT_PROPERTY = "PCP_RSA_EKCERT";
    public const string NCRYPT_PCP_RSA_EKNVCERT_PROPERTY = "PCP_RSA_EKNVCERT";
    public const string NCRYPT_PCP_ECC_EKPUB_PROPERTY = "PCP_ECC_EKPUB";
    public const string NCRYPT_PCP_ECC_EKCERT_PROPERTY = "PCP_ECC_EKCERT";
    public const string NCRYPT_PCP_ECC_EKNVCERT_PROPERTY = "PCP_ECC_EKNVCERT";
    public const string NCRYPT_PCP_SRKPUB_PROPERTY = "PCP_SRKPUB";
    public const string NCRYPT_PCP_PCRTABLE_PROPERTY = "PCP_PCRTABLE";
    public const string NCRYPT_PCP_CHANGEPASSWORD_PROPERTY = "PCP_CHANGEPASSWORD";
    public const string NCRYPT_PCP_PASSWORD_REQUIRED_PROPERTY = "PCP_PASSWORD_REQUIRED";
    public const string NCRYPT_PCP_USAGEAUTH_PROPERTY = "PCP_USAGEAUTH";
    public const string NCRYPT_PCP_MIGRATIONPASSWORD_PROPERTY = "PCP_MIGRATIONPASSWORD";
    public const string NCRYPT_PCP_EXPORT_ALLOWED_PROPERTY = "PCP_EXPORT_ALLOWED";
    public const string NCRYPT_PCP_STORAGEPARENT_PROPERTY = "PCP_STORAGEPARENT";
    public const string NCRYPT_PCP_PROVIDERHANDLE_PROPERTY = "PCP_PROVIDERMHANDLE";
    public const string NCRYPT_PCP_PLATFORMHANDLE_PROPERTY = "PCP_PLATFORMHANDLE";
    public const string NCRYPT_PCP_PLATFORM_BINDING_PCRMASK_PROPERTY = "PCP_PLATFORM_BINDING_PCRMASK";
    public const string NCRYPT_PCP_PLATFORM_BINDING_PCRDIGESTLIST_PROPERTY = "PCP_PLATFORM_BINDING_PCRDIGESTLIST";
    public const string NCRYPT_PCP_PLATFORM_BINDING_PCRDIGEST_PROPERTY = "PCP_PLATFORM_BINDING_PCRDIGEST";
    public const string NCRYPT_PCP_KEY_USAGE_POLICY_PROPERTY = "PCP_KEY_USAGE_POLICY";
    public const string NCRYPT_PCP_RSA_SCHEME_PROPERTY = "PCP_RSA_SCHEME";
    public const string NCRYPT_PCP_TPM12_IDBINDING_PROPERTY = "PCP_TPM12_IDBINDING";
    public const string NCRYPT_PCP_TPM12_IDBINDING_DYNAMIC_PROPERTY = "PCP_TPM12_IDBINDING_DYNAMIC";
    public const string NCRYPT_PCP_TPM12_IDACTIVATION_PROPERTY = "PCP_TPM12_IDACTIVATION";
    public const string NCRYPT_PCP_KEYATTESTATION_PROPERTY = "PCP_TPM12_KEYATTESTATION";
    public const string NCRYPT_PCP_ALTERNATE_KEY_STORAGE_LOCATION_PROPERTY = "PCP_ALTERNATE_KEY_STORAGE_LOCATION";
    public const string NCRYPT_PCP_PLATFORM_BINDING_PCRALGID_PROPERTY = "PCP_PLATFORM_BINDING_PCRALGID";
    public const string NCRYPT_PCP_HMAC_AUTH_POLICYREF = "PCP_HMAC_AUTH_POLICYREF";
    public const string NCRYPT_PCP_HMAC_AUTH_POLICYINFO = "PCP_HMAC_AUTH_POLICYINFO";
    public const string NCRYPT_PCP_HMAC_AUTH_NONCE = "PCP_HMAC_AUTH_NONCE";
    public const string NCRYPT_PCP_HMAC_AUTH_SIGNATURE = "PCP_HMAC_AUTH_SIGNATURE";
    public const string NCRYPT_PCP_HMAC_AUTH_TICKET = "PCP_HMAC_AUTH_TICKET";
    public const string NCRYPT_PCP_NO_DA_PROTECTION_PROPERTY = "PCP_NO_DA_PROTECTION";
    public const string NCRYPT_PCP_TPM_MANUFACTURER_ID_PROPERTY = "PCP_TPM_MANUFACTURER_ID";
    public const string NCRYPT_PCP_TPM_FW_VERSION_PROPERTY = "PCP_TPM_FW_VERSION";
    public const string NCRYPT_PCP_TPM2BNAME_PROPERTY = "PCP_TPM2BNAME";
    public const string NCRYPT_PCP_TPM_VERSION_PROPERTY = "PCP_TPM_VERSION";
    public const string NCRYPT_PCP_RAW_POLICYDIGEST_PROPERTY = "PCP_RAW_POLICYDIGEST";
    public const string NCRYPT_PCP_KEY_CREATIONHASH_PROPERTY = "PCP_KEY_CREATIONHASH";
    public const string NCRYPT_PCP_KEY_CREATIONTICKET_PROPERTY = "PCP_KEY_CREATIONTICKET";
    public const string NCRYPT_PCP_RSA_SCHEME_HASH_ALG_PROPERTY = "PCP_RSA_SCHEME_HASH_ALG";
    public const string NCRYPT_PCP_TPM_IFX_RSA_KEYGEN_PROHIBITED_PROPERTY = "PCP_TPM_IFX_RSA_KEYGEN_PROHIBITED";
    public const string NCRYPT_PCP_TPM_IFX_RSA_KEYGEN_VULNERABILITY_PROPERTY = "PCP_TPM_IFX_RSA_KEYGEN_VULNERABILITY";

    public const string NCRYPT_PCP_SESSIONID_PROPERTY = "PCP_SESSIONID";
    public const string NCRYPT_PCP_PSS_SALT_SIZE_PROPERTY = "PSS Salt Size";

    public const string NCRYPT_PCP_INTERMEDIATE_CA_EKCERT_PROPERTY = "PCP_INTERMEDIATE_CA_EKCERT";
    public const string NCRYPT_PCP_PCRTABLE_ALGORITHM_PROPERTY = "PCP_PCRTABLE_ALGORITHM";
    public const string NCRYPT_PCP_SYMMETRIC_KEYBITS_PROPERTY = "PCP_SYMMETRIC_KEYBITS";
}