// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436
namespace RS.Schannel.Manager.API;

[Flags]
public enum CRYPT_OID_FLAG : uint
{
    CRYPT_OID_INHIBIT_SIGNATURE_FORMAT_FLAG = 0x00000001U,
    CRYPT_OID_USE_PUBKEY_PARA_FOR_PKCS7_FLAG = 0x00000002U,
    CRYPT_OID_NO_NULL_ALGORITHM_PARA_FLAG = 0x00000004U,

    CRYPT_OID_PUBKEY_SIGN_ONLY_FLAG = 0x80000000U,
    CRYPT_OID_PUBKEY_ENCRYPT_ONLY_FLAG = 0x40000000U,
    CRYPT_OID_USE_CURVE_NAME_FOR_ENCODE_FLAG = 0x20000000U,
    CRYPT_OID_USE_CURVE_PARAMETERS_FOR_ENCODE_FLAG = 0x10000000U
}