namespace RS.Schannel.Manager.API;

public enum CRYPT_OID_GROUP_ID : uint
{
    CRYPT_ALL_OID_GROUP_ID = 0U,
    CRYPT_HASH_ALG_OID_GROUP_ID = 1U,
    CRYPT_ENCRYPT_ALG_OID_GROUP_ID = 2U,
    CRYPT_PUBKEY_ALG_OID_GROUP_ID = 3U,
    CRYPT_SIGN_ALG_OID_GROUP_ID = 4U,
    CRYPT_RDN_ATTR_OID_GROUP_ID = 5U,
    CRYPT_EXT_OR_ATTR_OID_GROUP_ID = 6U,
    CRYPT_ENHKEY_USAGE_OID_GROUP_ID = 7U,
    CRYPT_POLICY_OID_GROUP_ID = 8U,
    CRYPT_TEMPLATE_OID_GROUP_ID = 9U,
    CRYPT_KDF_OID_GROUP_ID = 10U,
    CRYPT_LAST_OID_GROUP_ID = 10U,

    CRYPT_FIRST_ALG_OID_GROUP_ID = CRYPT_HASH_ALG_OID_GROUP_ID,
    CRYPT_LAST_ALG_OID_GROUP_ID = CRYPT_SIGN_ALG_OID_GROUP_ID
}