// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436
namespace RS.Schannel.Manager.API;

internal class EllipticCurveNames
{
    public const string BCRYPT_ECC_CURVE_BRAINPOOLP160R1 = "brainpoolP160r1";
    public const string BCRYPT_ECC_CURVE_BRAINPOOLP160T1 = "brainpoolP160t1";
    public const string BCRYPT_ECC_CURVE_BRAINPOOLP192R1 = "brainpoolP192r1";
    public const string BCRYPT_ECC_CURVE_BRAINPOOLP192T1 = "brainpoolP192t1";
    public const string BCRYPT_ECC_CURVE_BRAINPOOLP224R1 = "brainpoolP224r1";
    public const string BCRYPT_ECC_CURVE_BRAINPOOLP224T1 = "brainpoolP224t1";
    public const string BCRYPT_ECC_CURVE_BRAINPOOLP256R1 = "brainpoolP256r1";
    public const string BCRYPT_ECC_CURVE_BRAINPOOLP256T1 = "brainpoolP256t1";
    public const string BCRYPT_ECC_CURVE_BRAINPOOLP320R1 = "brainpoolP320r1";
    public const string BCRYPT_ECC_CURVE_BRAINPOOLP320T1 = "brainpoolP320t1";
    public const string BCRYPT_ECC_CURVE_BRAINPOOLP384R1 = "brainpoolP384r1";
    public const string BCRYPT_ECC_CURVE_BRAINPOOLP384T1 = "brainpoolP384t1";
    public const string BCRYPT_ECC_CURVE_BRAINPOOLP512R1 = "brainpoolP512r1";
    public const string BCRYPT_ECC_CURVE_BRAINPOOLP512T1 = "brainpoolP512t1";

    public const string BCRYPT_ECC_CURVE_25519 = "curve25519";

    public const string BCRYPT_ECC_CURVE_EC192WAPI = "ec192wapi";

    public const string BCRYPT_ECC_CURVE_NISTP192 = "nistP192";
    public const string BCRYPT_ECC_CURVE_NISTP224 = "nistP224";
    public const string BCRYPT_ECC_CURVE_NISTP256 = "nistP256";
    public const string BCRYPT_ECC_CURVE_NISTP384 = "nistP384";
    public const string BCRYPT_ECC_CURVE_NISTP521 = "nistP521";

    public const string BCRYPT_ECC_CURVE_NUMSP256T1 = "numsP256t1";
    public const string BCRYPT_ECC_CURVE_NUMSP384T1 = "numsP384t1";
    public const string BCRYPT_ECC_CURVE_NUMSP512T1 = "numsP512t1";

    public const string BCRYPT_ECC_CURVE_SECP160K1 = "secP160k1";
    public const string BCRYPT_ECC_CURVE_SECP160R1 = "secP160r1";
    public const string BCRYPT_ECC_CURVE_SECP160R2 = "secP160r2";
    public const string BCRYPT_ECC_CURVE_SECP192K1 = "secP192k1";
    public const string BCRYPT_ECC_CURVE_SECP192R1 = "secP192r1";
    public const string BCRYPT_ECC_CURVE_SECP224K1 = "secP224k1";
    public const string BCRYPT_ECC_CURVE_SECP224R1 = "secP224r1";
    public const string BCRYPT_ECC_CURVE_SECP256K1 = "secP256k1";
    public const string BCRYPT_ECC_CURVE_SECP256R1 = "secP256r1";
    public const string BCRYPT_ECC_CURVE_SECP384R1 = "secP384r1";
    public const string BCRYPT_ECC_CURVE_SECP521R1 = "secP521r1";

    public const string BCRYPT_ECC_CURVE_WTLS7 = "wtls7";
    public const string BCRYPT_ECC_CURVE_WTLS9 = "wtls9";
    public const string BCRYPT_ECC_CURVE_WTLS12 = "wtls12";

    public const string BCRYPT_ECC_CURVE_X962P192V1 = "x962P192v1";
    public const string BCRYPT_ECC_CURVE_X962P192V2 = "x962P192v2";
    public const string BCRYPT_ECC_CURVE_X962P192V3 = "x962P192v3";
    public const string BCRYPT_ECC_CURVE_X962P239V1 = "x962P239v1";
    public const string BCRYPT_ECC_CURVE_X962P239V2 = "x962P239v2";
    public const string BCRYPT_ECC_CURVE_X962P239V3 = "x962P239v3";
    public const string BCRYPT_ECC_CURVE_X962P256V1 = "x962P256v1";

    public string GetName(string identifier)
    {
        var dictionary = new Dictionary<string, string>
        {
            { BCRYPT_ECC_CURVE_BRAINPOOLP160R1, nameof(BCRYPT_ECC_CURVE_BRAINPOOLP160R1) },
            { BCRYPT_ECC_CURVE_BRAINPOOLP160T1, nameof(BCRYPT_ECC_CURVE_BRAINPOOLP160T1) },
            { BCRYPT_ECC_CURVE_BRAINPOOLP192R1, nameof(BCRYPT_ECC_CURVE_BRAINPOOLP192R1) },
            { BCRYPT_ECC_CURVE_BRAINPOOLP192T1, nameof(BCRYPT_ECC_CURVE_BRAINPOOLP192T1) },
            { BCRYPT_ECC_CURVE_BRAINPOOLP224R1, nameof(BCRYPT_ECC_CURVE_BRAINPOOLP224R1) },
            { BCRYPT_ECC_CURVE_BRAINPOOLP224T1, nameof(BCRYPT_ECC_CURVE_BRAINPOOLP224T1) },
            { BCRYPT_ECC_CURVE_BRAINPOOLP256R1, nameof(BCRYPT_ECC_CURVE_BRAINPOOLP256R1) },
            { BCRYPT_ECC_CURVE_BRAINPOOLP256T1, nameof(BCRYPT_ECC_CURVE_BRAINPOOLP256T1) },
            { BCRYPT_ECC_CURVE_BRAINPOOLP320R1, nameof(BCRYPT_ECC_CURVE_BRAINPOOLP320R1) },
            { BCRYPT_ECC_CURVE_BRAINPOOLP320T1, nameof(BCRYPT_ECC_CURVE_BRAINPOOLP320T1) },
            { BCRYPT_ECC_CURVE_BRAINPOOLP384R1, nameof(BCRYPT_ECC_CURVE_BRAINPOOLP384R1) },
            { BCRYPT_ECC_CURVE_BRAINPOOLP384T1, nameof(BCRYPT_ECC_CURVE_BRAINPOOLP384T1) },
            { BCRYPT_ECC_CURVE_BRAINPOOLP512R1, nameof(BCRYPT_ECC_CURVE_BRAINPOOLP512R1) },
            { BCRYPT_ECC_CURVE_BRAINPOOLP512T1, nameof(BCRYPT_ECC_CURVE_BRAINPOOLP512T1) },
            { BCRYPT_ECC_CURVE_25519, nameof(BCRYPT_ECC_CURVE_25519) },
            { BCRYPT_ECC_CURVE_EC192WAPI, nameof(BCRYPT_ECC_CURVE_EC192WAPI) },
            { BCRYPT_ECC_CURVE_NISTP192, nameof(BCRYPT_ECC_CURVE_NISTP192) },
            { BCRYPT_ECC_CURVE_NISTP224, nameof(BCRYPT_ECC_CURVE_NISTP224) },
            { BCRYPT_ECC_CURVE_NISTP256, nameof(BCRYPT_ECC_CURVE_NISTP256) },
            { BCRYPT_ECC_CURVE_NISTP384, nameof(BCRYPT_ECC_CURVE_NISTP384) },
            { BCRYPT_ECC_CURVE_NISTP521, nameof(BCRYPT_ECC_CURVE_NISTP521) },
            { BCRYPT_ECC_CURVE_NUMSP256T1, nameof(BCRYPT_ECC_CURVE_NUMSP256T1) },
            { BCRYPT_ECC_CURVE_NUMSP384T1, nameof(BCRYPT_ECC_CURVE_NUMSP384T1) },
            { BCRYPT_ECC_CURVE_NUMSP512T1, nameof(BCRYPT_ECC_CURVE_NUMSP512T1) },
            { BCRYPT_ECC_CURVE_SECP160K1, nameof(BCRYPT_ECC_CURVE_SECP160K1) },
            { BCRYPT_ECC_CURVE_SECP160R1, nameof(BCRYPT_ECC_CURVE_SECP160R1) },
            { BCRYPT_ECC_CURVE_SECP160R2, nameof(BCRYPT_ECC_CURVE_SECP160R2) },
            { BCRYPT_ECC_CURVE_SECP192K1, nameof(BCRYPT_ECC_CURVE_SECP192K1) },
            { BCRYPT_ECC_CURVE_SECP192R1, nameof(BCRYPT_ECC_CURVE_SECP192R1) },
            { BCRYPT_ECC_CURVE_SECP224K1, nameof(BCRYPT_ECC_CURVE_SECP224K1) },
            { BCRYPT_ECC_CURVE_SECP224R1, nameof(BCRYPT_ECC_CURVE_SECP224R1) },
            { BCRYPT_ECC_CURVE_SECP256K1, nameof(BCRYPT_ECC_CURVE_SECP256K1) },
            { BCRYPT_ECC_CURVE_SECP256R1, nameof(BCRYPT_ECC_CURVE_SECP256R1) },
            { BCRYPT_ECC_CURVE_SECP384R1, nameof(BCRYPT_ECC_CURVE_SECP384R1) },
            { BCRYPT_ECC_CURVE_SECP521R1, nameof(BCRYPT_ECC_CURVE_SECP521R1) },
            { BCRYPT_ECC_CURVE_WTLS7, nameof(BCRYPT_ECC_CURVE_WTLS7) },
            { BCRYPT_ECC_CURVE_WTLS9, nameof(BCRYPT_ECC_CURVE_WTLS9) },
            { BCRYPT_ECC_CURVE_WTLS12, nameof(BCRYPT_ECC_CURVE_WTLS12) },
            { BCRYPT_ECC_CURVE_X962P192V1, nameof(BCRYPT_ECC_CURVE_X962P192V1) },
            { BCRYPT_ECC_CURVE_X962P192V2, nameof(BCRYPT_ECC_CURVE_X962P192V2) },
            { BCRYPT_ECC_CURVE_X962P192V3, nameof(BCRYPT_ECC_CURVE_X962P192V3) },
            { BCRYPT_ECC_CURVE_X962P239V1, nameof(BCRYPT_ECC_CURVE_X962P239V1) },
            { BCRYPT_ECC_CURVE_X962P239V2, nameof(BCRYPT_ECC_CURVE_X962P239V2) },
            { BCRYPT_ECC_CURVE_X962P239V3, nameof(BCRYPT_ECC_CURVE_X962P239V3) },
            { BCRYPT_ECC_CURVE_X962P256V1, nameof(BCRYPT_ECC_CURVE_X962P256V1) }
        };

        return dictionary[identifier];
    }
}