// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
namespace RS.Schannel.Manager.API;

using Windows.Win32;

[Flags]
internal enum GPO_OPTION : uint
{
    // Group Policy Object option flags
    GPO_OPTION_NONE = 0U,
    GPO_OPTION_DISABLE_USER = PInvoke.GPO_OPTION_DISABLE_USER, // The user portion of this GPO is disabled
    GPO_OPTION_DISABLE_MACHINE = PInvoke.GPO_OPTION_DISABLE_MACHINE // The machine portion of this GPO is disabled
}