// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Windows.Win32;

public enum PriorityListPosition : uint
{
    CRYPT_PRIORITY_TOP = 0U, // to add a function to the top of the prioritized list.

    CRYPT_PRIORITY_BOTTOM = 0xFFFFFFFF // to add a function to the bottom of the prioritized list.
}