// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
namespace CipherPunk;

[Flags]
public enum SchannelCertificateMappingMethod
{
    Subject_Issuer = 0x0001,
    IssuerCertificate = 0x0002,
    UPN = 0x0004,
    S4U2Self = 0x0008,
    S4U2SelfExplicit = 0x0010
}