// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
namespace CipherPunk;

public enum SchannelProtocol
{
    DTLS1_0,
    DTLS1_2,
    UNIHELLO,
    PCT1_0,
    SSL2_0,
    SSL3_0,
    TLS1_0,
    TLS1_1,
    TLS1_2,
    TLS1_3
}