// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
    internal static partial class PInvoke
    {
        internal static Microsoft.Win32.SafeHandles.SafeFileHandle GetCurrentProcessToken()
        {
            winmdroot.Foundation.HANDLE __result = new((IntPtr)(-4));
            return new Microsoft.Win32.SafeHandles.SafeFileHandle(__result, ownsHandle: false);
        }

        internal static Microsoft.Win32.SafeHandles.SafeFileHandle GetCurrentThreadToken()
        {
            winmdroot.Foundation.HANDLE __result = new((IntPtr)(-5));
            return new Microsoft.Win32.SafeHandles.SafeFileHandle(__result, ownsHandle: false);
        }

        internal static Microsoft.Win32.SafeHandles.SafeFileHandle GetCurrentThreadEffectiveToken()
        {
            winmdroot.Foundation.HANDLE __result = new((IntPtr)(-6));
            return new Microsoft.Win32.SafeHandles.SafeFileHandle(__result, ownsHandle: false);
        }
    }
}