// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CipherPunk;

public enum SslCipherSuite : uint
{
    SSL_CK_RC4_128_WITH_MD5 = 0x010080,
    SSL_CK_RC4_128_EXPORT40_WITH_MD5 = 0x020080,
    SSL_CK_RC2_128_CBC_WITH_MD5 = 0x030080,
    SSL_CK_RC2_128_CBC_EXPORT40_WITH_MD5 = 0x040080,
    SSL_CK_IDEA_128_CBC_WITH_MD5 = 0x050080,
    SSL_CK_DES_64_CBC_WITH_MD5 = 0x060040,
    SSL_CK_DES_64_CBC_WITH_SHA = 0x060140,
    SSL_CK_DES_192_EDE3_CBC_WITH_MD5 = 0x0700C0,
    SSL_CK_DES_192_EDE3_CBC_WITH_SHA = 0x0701c0,
    SSL_CK_RC4_64_WITH_MD5 = 0x080080,
    SSL_CK_DES_64_CFB64_WITH_MD5_1 = 0xff0800,
    SSL_CK_NULL = 0xff0810
}