// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CipherPunk;

public enum TlsAlertLevel : byte
{
    warning = 0x01,
    fatal = 0x02
}