// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CipherPunk;

public enum TlsVersion : ushort
{
    SSL2_PROTOCOL_VERSION = Windows.Win32.SslProviderProtocolId.SSL2_PROTOCOL_VERSION,
    SSL3_PROTOCOL_VERSION = Windows.Win32.SslProviderProtocolId.SSL3_PROTOCOL_VERSION,
    TLS1_0_PROTOCOL_VERSION = Windows.Win32.SslProviderProtocolId.TLS1_0_PROTOCOL_VERSION,
    TLS1_1_PROTOCOL_VERSION = Windows.Win32.SslProviderProtocolId.TLS1_1_PROTOCOL_VERSION,
    TLS1_2_PROTOCOL_VERSION = Windows.Win32.SslProviderProtocolId.TLS1_2_PROTOCOL_VERSION,
    TLS1_3_PROTOCOL_VERSION = Windows.Win32.SslProviderProtocolId.TLS1_3_PROTOCOL_VERSION
}